MIT-Mobile/MIT-Mobile-for-iOS

Modules/ShuttleTrack/MITShuttleMapViewController.m, Modules/Tours/MITToursStopDetailViewController~iphone.xib
=> 3.6/dev intrepid lwright

Modules/ShuttleTrack/MITShuttleHomeViewController.m, Modules/ShuttleTrack/MITShuttleMapViewController.m
Fixes for shuttles home and stop VCs appropriately adding/removing prediction dependencies
=> 3.6/ross shuttles predictions request fix

External/SMCalloutView/SMCalloutView.m, Modules/ShuttleTrack/MITShuttleMapViewController.m, Modules/ShuttleTrack/MITShuttleStopViewController.m
Different solution to the SMCalloutView problem. Makes more sense to me
=> 3.6/ross smcallout margin fix

Modules/Dining/MITDiningMapsViewController.m
Highlight bubble when selected.
Disable double tapping of annotation to go to detail screen.
Add chevron to annotation bubble
=> Make iPhone Dining Annotations Act Like Maps Annotations #596

Resources/news/news_story_iPad_template.html, Resources/news/news_story_template.html
Cleaner to wrap the two p tags in a div instead of bookending them with p tags.
Suggestion by @justinanderson
References Issue #563
=> Cleaner to wrap the two p tags in a div instead of bookending them with p tags

Modules/News/View Controllers/MITNewsGridViewController.m, Modules/News/View Controllers/MITNewsViewController.m
References 
Fresh install with no internet will crash app #686
News iOS 7 auto load more stories Does Not Work #690
=> 3.6/experimental/collection view loading cell

App Delegate/MITSlidingViewController.h, App Delegate/MITSlidingViewController.m, App Delegate/MIT_MobileAppDelegate.m
=> Fixes app crash when reopening iPad app after exiting it with a modal module visible.

App Delegate/MIT_MobileAppDelegate.m
Remove local notification from saved list when acknowledging local notification #708
=> Remove local notification from saved list when acknowledging local notification #708

App Delegate/MITSlidingViewController.m
=> Disable drag from anywhere drawer gesture.

MIT Mobile.xcodeproj/project.pbxproj, Modules/Dining/MITDiningHouseMealListViewController.h, Modules/Dining/MITDiningHouseMealListViewController.m, Modules/Dining/MITDiningHouseMealListViewController.xib, Modules/Dining/MITDiningHouseVenueDetailViewController.m
=> Added dining menus empty table message #721

App Delegate/MITSlidingViewController.m
Allow the pan gesture to cancel touches in it's view and rework the initial triggering conditions for the gesture.
=> Tweak the drawer's pan gesture triggering. #703

MIT Mobile.xcodeproj/project.pbxproj, Modules/ShuttleTrack/MITShuttleDataSource.h, Modules/ShuttleTrack/MITShuttleDataSource.m, Modules/ShuttleTrack/MITShuttleHomeViewController.m, Modules/ShuttleTrack/MITShuttleMapBusAnnotationView.h, Modules/ShuttleTrack/MITShuttleMapBusAnnotationView.m, Modules/ShuttleTrack/MITShuttleMapViewController.h, Modules/ShuttleTrack/MITShuttleMapViewController.m, Modules/ShuttleTrack/MITShuttlePredictionLoader.m, Modules/ShuttleTrack/MITShuttleRouteContainerViewController.m, Modules/ShuttleTrack/MITShuttleRouteViewController.m, Modules/ShuttleTrack/MITShuttleRoutesDataSource.h, Modules/ShuttleTrack/MITShuttleRoutesDataSource.m, Modules/ShuttleTrack/MITShuttleStopViewController.m, Modules/ShuttleTrack/MITShuttleVehiclesDataSource.h, Modules/ShuttleTrack/MITShuttleVehiclesDataSource.m, Modules/ShuttleTrack/Models/Entities/MITShuttleVehicle.h, Modules/ShuttleTrack/Models/Entities/MITShuttleVehicle.m, Modules/ShuttleTrack/Models/MITShuttleController.h, Modules/ShuttleTrack/Models/MITShuttleController.m
Async for shuttles maps for #425, fixes for #680, #679, general refactoring and betterment
=> 3.6/ross shuttles async

Modules/QR Reader/MITScannerMgr.h, Modules/QR Reader/MITScannerMgr.m
=> Scanner intermittently fails to capture and save image.

App Delegate/MITSlidingViewController.m
=> Tweak the modal dismiss tap gesture recognition in iOS 8. #736.

Modules/ShuttleTrack/MITShuttleMapViewController.m, Modules/ShuttleTrack/MITShuttleRouteViewController.m, Modules/ShuttleTrack/Models/MITShuttleDataModel.xcdatamodeld/MITShuttleDataModel.xcdatamodel/contents
Fixes for map annotations that were not showing up on iphone
=> 3.6/ross orphaned stop fix

Modules/ShuttleTrack/MITShuttleMapViewController.m
=> Changed UI for iPad shuttles maps callout to better match design

Modules/ShuttleTrack/MITShuttleMapViewController.m, Modules/ShuttleTrack/MITShuttleStopViewController.h, Modules/ShuttleTrack/MITShuttleStopViewController.m
=> Fixed iPad shuttles map callout layout for iOS 7 & 8 #718

Common/Core Data/MITShuttlesResource.m, Modules/ShuttleTrack/MITShuttleHomeViewController.m, Modules/ShuttleTrack/MITShuttleMapViewController.m, Modules/ShuttleTrack/MITShuttlePredictionLoader.h, Modules/ShuttleTrack/MITShuttlePredictionLoader.m, Modules/ShuttleTrack/MITShuttleRouteViewController.m, Modules/ShuttleTrack/MITShuttleRoutesDataSource.m, Modules/ShuttleTrack/MITShuttleStopViewController.m, Modules/ShuttleTrack/Models/Entities/MITShuttlePredictionList.h, Modules/ShuttleTrack/Models/Entities/MITShuttlePredictionList.m, Modules/ShuttleTrack/Models/Entities/MITShuttleRoute.h, Modules/ShuttleTrack/Models/Entities/MITShuttleRoute.m, Modules/ShuttleTrack/Models/Entities/MITShuttleStop.h, Modules/ShuttleTrack/Models/Entities/MITShuttleStop.m, Modules/ShuttleTrack/Models/Entities/MITShuttleVehicleList.h, Modules/ShuttleTrack/Models/Entities/MITShuttleVehicleList.m, Modules/ShuttleTrack/Models/MITShuttleController.m, Modules/ShuttleTrack/Models/MITShuttleDataModel.xcdatamodeld/MITShuttleDataModel.xcdatamodel/contents
Fixes for #735 and #671, with efficiency and architecture improvements for several parts of shuttles.
=> 3.6/ross shuttles prediction staleness

Modules/Dining/MITDiningDataModel.xcdatamodeld/MITDiningDataModel.xcdatamodel/contents, Modules/Dining/MITDiningHouseDay.m, Modules/Dining/MITDiningHouseVenueDetailViewController.m, Modules/Dining/MITDiningMeal.m
Should resolve #789, but I'm not very familiar with the new Dining code so this could use the eye of someone who is.
=> 4.0/dining meal order

Modules/Dining/MITDiningDietaryFlagListViewController.m
=> Fixed filter legend popover in iPad dining

MIT Mobile.xcodeproj/project.pbxproj, Modules/Marty/View Controllers/MITMartyPadHomeViewController.m, Modules/Marty/Views/MITMartyCalloutContentView.h, Modules/Marty/Views/MITMartyCalloutContentView.m, Modules/Marty/Views/MITMartyCalloutContentView.xib
Added Annotation Bubble for iPhone and iPad #809 #818 RES-82 RES-84 RES-88
=> Added Annotation Bubble for iPhone and iPad #809 #818 RES-82 RES-84 RES-88

Modules/ShuttleTrack/MITShuttleHomeViewController.m
=> Don't show refresh control in Shuttles unless user initiates a refresh.

Common/UI/NavigationController/BackButtonOverride/UIViewController+BackButtonHandler.h, Common/UI/NavigationController/BackButtonOverride/UIViewController+BackButtonHandler.m, MIT Mobile.xcodeproj/project.pbxproj, Modules/ShuttleTrack/MITShuttleRouteContainerViewController.m
=> Changing navigation flow iPhone shuttles #847

Modules/Dining/MITDiningHallMealCollectionHeader.m, Modules/Dining/MITDiningHallMealCollectionHeader.xib
=> Updating open closed behavior and layout of iPad dining house venue header

MIT Mobile.xcodeproj/project.pbxproj, Modules/Marty/MITMartyMapViewController.h, Modules/Marty/MITMartyMapViewController.m, Modules/Marty/MITMartyMapViewController.xib, Modules/Marty/Marty_pad.storyboard, Modules/Marty/View Controllers/MITMartyPadHomeViewController.m
Removed map code from iPad class and made standalone map class
=> Marty map class

Modules/Marty/MITMartyMapViewController.m, Modules/Marty/MITMartyRecentSearchController.xib, Modules/Marty/Model/MITMartyResourceDataSource.h, Modules/Marty/Model/MITMartyResourceDataSource.m, Modules/Marty/View Controllers/MITMartyPadHomeViewController.m, Modules/Marty/View Controllers/MITMartyRecentSearchController.h, Modules/Marty/View Controllers/MITMartyRecentSearchController.m, Modules/Marty/Views/MITMartyCalloutContentView.m, Modules/Marty/Views/MITMartyCalloutContentView.xib, Modules/Marty/Views/MITMartyResourceView.m
* Graphical corruption if the previous searches popover was closed while the 'Clear' UIActionSheet was visible
* Height/width sizing issues with the resource table view cells
* The recent searches popover was closed when the user tapped the 'Clear' button
* General refactoring and code cleanup of the root iPad Marty view controller
=> Bug fixes and refactoring of the iPad Marty view controller

Modules/Marty/View Controllers/MITMartyPadHomeViewController.m
when clicking the x reset recents
still need to call filterResultsUsingString when searchString is "" to update Recents List
=> Marty recent search

Modules/Mobius/Model/MITMobiusResource.m, Modules/Mobius/Model/MITMobiusResourceAttributeValue.m, Modules/Mobius/View Controllers/MITMobiusDetailTableViewController.m
=> Make a permanent fix for detail blank description rows

MIT Mobile.xcodeproj/project.pbxproj, MIT Mobile.xcodeproj/xcshareddata/xcschemes/MIT Mobile.xcscheme, MIT_Mobile-Info.plist
=> Update bundle identifier for Möbius branch testing. Fixes #895.

Modules/Mobius/Model/MITMobiusResourceDataSource.m
Changing server from dev to test so dev can be updated.
=> changing server from dev to test #900

Modules/Mobius/View Controllers/MITMobiusDetailTableViewController.m
=> implementing clicking on detail view's location cell to open maps module with resource's location #882

Modules/Mobius/MITMobiusDetailContainerViewController.h, Modules/Mobius/MITMobiusDetailContainerViewController.m, Modules/Mobius/MITMobiusMapViewController.m, Modules/Mobius/Model/MITMobiusResourceDataSource.h, Modules/Mobius/Model/MITMobiusResourceDataSource.m, Modules/Mobius/View Controllers/MITMobiusRootPhoneViewController.m
Switched from passing in an array of resources to using a delegate to handle the requests for paging data.
=> Changes to the detail paging process. #877

Modules/News/Model/MITNewsCategory.h, Modules/News/Model/MITNewsCategory.m, Modules/News/Model/MITNewsStory.m
Fixes news categorying ordering issue #935
=> Fixes news categorying ordering issue #935

Common/MapCallout/MITCalloutView.m, Modules/Campus Map/MITMapHomeViewController.m, Modules/Dining/MITDiningMapsViewController.m, Modules/ShuttleTrack/MITShuttleMapViewController.m, Modules/Tours/MITToursMapViewController.m
=> Ross callout fixes

Modules/Mobius/MITMobiusDetailTableViewController.m
=> change color of segmented control to dark gray #954
